version: 1.0.7.{build}
skip_tags: true
#install:
#    - nuget restore -SolutionDirectory Source\AutoTest.Exceptions
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: detailed
environment:
    COVERALLS_REPO_TOKEN:  
       secure: nir5STPp1EOEkFP0DaS23pd2rHYzvEiturTJQ5ewVKVoCr+6Ei6f57Stihm/r/re
after_test: 
  - ps: dir 
  - nuget.exe restore -PackagesDirectory C:\projects\autotest-exceptions\Source\AutoTest.Exceptions\packages\
  - Source\AutoTest.Exceptions\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:"Source\AutoTest.Exceptions\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:""Source\AutoTest.Exceptions\AutoTest.Exceptions.UnitTests\bin\$env:CONFIGURATION\AutoTest.Exceptions.UnitTests.dll"" /noshadow" -output:opencoverCoverage.xml
  - Source\AutoTest.Exceptions\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
deploy:
- provider: NuGet
  api_key:
    secure: sgFlZQ6SSawwtiKcN23uO3hdwEGvy8M4hA8ye2iTAPdmz4gByofx2ZljpJHZ+Pm3
  on:
    branch: master