version: 1.0.{build}
skip_tags: true
install:
    - nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: detailed
environment:
    COVERALLS_REPO_TOKEN:  
       secure: nir5STPp1EOEkFP0DaS23pd2rHYzvEiturTJQ5ewVKVoCr+6Ei6f57Stihm/r/re
after_test: 
    - Source\AutoTest.Exceptions\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"Source\AutoTest.Exceptions\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  Source\AutoTest.Exceptions\AutoTest.Exceptions.UnitTests\bin\Debug\AutoTest.Exceptions.UnitTests.dll" -output:coverage.xml
    - Source\AutoTest.Exceptions\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover coverage.xml- provider: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: sgFlZQ6SSawwtiKcN23uO3hdwEGvy8M4hA8ye2iTAPdmz4gByofx2ZljpJHZ+Pm3
  on:
    branch: master